SOFT:=nginx
VER:=1.6.0
SUF:=tar.gz
URL:=http://nginx.org/download/nginx-1.6.0.tar.gz
URL2:=http://nginx.org/download/nginx-1.2.9.tar.gz
MD5:=8efa354f1c3c2ccf434a50d3fbe82340
TAR:=$(SOFT)-$(VER).$(SUF)
DIR:=$(SOFT)-$(VER)

all:
	@echo $(TAR)

config:

build:

install:

pre:

unzip:
	tar jxvf $(TAR)

wget:
	wget -O $(TAR) $(URL)

